export const seedActionTiers = [
  {
    tierLevel: 1,
    name: "Light Switches",
    icon: "🟢",
    color: "#5B8C5A",
    unlockThreshold: 0,
    description: "Near-zero effort. Immediate. Often saves money. Small switches that start your carbon journey.",
  },
  {
    tierLevel: 2,
    name: "Habit Builders",
    icon: "🟡",
    color: "#C67B5C",
    unlockThreshold: 5,
    description: "Requires repeated commitment. Builds identity and integrates carbon reduction into daily routines.",
  },
  {
    tierLevel: 3,
    name: "Lifestyle Levers",
    icon: "🔴",
    color: "#7BA7BC",
    unlockThreshold: 12,
    description: "High-impact structural decisions. Presented after establishing solid sustainability habits.",
  },
];

export const seedActions = [
  // ─── TIER 1: LIGHT SWITCHES ───
  {
    title: "Swap to oat milk",
    description: "Swap almond or dairy milk with local oat milk in your coffee or cereal. Dairy milk emits 3x more carbon than plant milk.",
    impactDescription: "This swap, done weekly for a year, is the equivalent of keeping one mature oak tree standing.",
    category: "diet",
    estimatedCo2eReductionKg: "2.1000",
    feasibilityScore: 95,
    tierLevel: 1,
    isActive: true,
  },
  {
    title: "Lower thermostat by 2°F",
    description: "Turn down your heating thermostat by 2°F at night. Put on a warm sweater instead. Your furnace will consume 8% less gas/electricity.",
    impactDescription: "Saves ~150 kg CO2e over a winter season, and cuts about $40 off your energy bill.",
    category: "energy",
    estimatedCo2eReductionKg: "2.5000",
    feasibilityScore: 90,
    tierLevel: 1,
    isActive: true,
  },
  {
    title: "Select Amazon 'No-Rush' shipping",
    description: "When ordering on Amazon, select 'No-Rush Shipping'. It allows Amazon to consolidate packages and optimize delivery truck routes.",
    impactDescription: "Reduces delivery carbon footprint by 30%, saving ~1 kg CO2e per package.",
    category: "shopping",
    estimatedCo2eReductionKg: "1.0000",
    feasibilityScore: 98,
    tierLevel: 1,
    isActive: true,
  },
  {
    title: "Shorter shower by 2 minutes",
    description: "Set a timer to reduce your shower time by 2 minutes. Hot water requires substantial electricity or natural gas heating.",
    impactDescription: "Saves ~0.8 kg CO2e and 20 liters of fresh water per shower.",
    category: "energy",
    estimatedCo2eReductionKg: "0.8000",
    feasibilityScore: 88,
    tierLevel: 1,
    isActive: true,
  },
  {
    title: "Unplug standby electronics",
    description: "Unplug unused chargers, TVs, and gaming consoles when going to sleep or out of town. Phantom draw account for 10% of home energy bills.",
    impactDescription: "Avoids ~0.5 kg CO2e per day in standby electric waste.",
    category: "energy",
    estimatedCo2eReductionKg: "0.5000",
    feasibilityScore: 85,
    tierLevel: 1,
    isActive: true,
  },
  {
    title: "Swap dairy cheese for plant-based cheese",
    description: "Swap dairy cheese with a plant-based cheese alternative. Dairy cattle farming is highly resource-intensive, emitting 4x more carbon than plant-based cheese.",
    impactDescription: "Avoids 3.5 kg CO2e in a single food swap.",
    category: "diet",
    estimatedCo2eReductionKg: "3.5000",
    feasibilityScore: 80,
    tierLevel: 1,
    isActive: true,
  },
  {
    title: "Wash laundry in cold water",
    description: "Set your washing machine to 30°C (cold) instead of 40°C or 60°C. 90% of a washing machine's energy goes into heating water.",
    impactDescription: "Saves ~0.6 kg CO2e per load of laundry.",
    category: "energy",
    estimatedCo2eReductionKg: "0.6000",
    feasibilityScore: 92,
    tierLevel: 1,
    isActive: true,
  },
  {
    title: "Take public transit for a short trip",
    description: "For your next trip under 5 miles, take the bus, metro, or tram instead of driving. Transit shares emissions across hundreds of riders.",
    impactDescription: "Reduces transit carbon by ~1.5 kg CO2e per trip.",
    category: "transport",
    estimatedCo2eReductionKg: "1.5000",
    feasibilityScore: 78,
    tierLevel: 1,
    isActive: true,
  },
  {
    title: "Use reusable grocery bags",
    description: "Bring canvas bags to the store instead of purchasing plastic or paper single-use bags. Avoids microplastic and manufacturing emissions.",
    impactDescription: "Saves ~0.2 kg CO2e per shopping trip.",
    category: "shopping",
    estimatedCo2eReductionKg: "0.2000",
    feasibilityScore: 95,
    tierLevel: 1,
    isActive: true,
  },
  {
    title: "Switch 3 light bulbs to LEDs",
    description: "Replace your 3 most used incandescent light bulbs with energy-efficient LEDs. LEDs use 85% less energy and last 25 times longer.",
    impactDescription: "Saves ~45 kg CO2e per year of regular bulb usage.",
    category: "energy",
    estimatedCo2eReductionKg: "1.2000",
    feasibilityScore: 90,
    tierLevel: 1,
    isActive: true,
  },

  // ─── TIER 2: HABIT BUILDERS ───
  {
    title: "Choose local seasonal produce",
    description: "Buy fruits and vegetables that are locally grown and in season, avoiding the high carbon footprint of long-distance air freight and imports.",
    impactDescription: "Reduces food transport emissions, saving ~4.0 kg CO2e per grocery trip.",
    category: "diet",
    estimatedCo2eReductionKg: "4.0000",
    feasibilityScore: 85,
    tierLevel: 2,
    isActive: true,
  },
  {
    title: "Bike Wednesdays",
    description: "Commit to commuting to work or school via bicycle every Wednesday instead of driving.",
    impactDescription: "Over a year, this cuts 200 commutes, avoiding ~300 kg CO2e and saving $150 in fuel.",
    category: "transport",
    estimatedCo2eReductionKg: "6.0000",
    feasibilityScore: 68,
    tierLevel: 2,
    isActive: true,
  },
  {
    title: "Buy second-hand clothing for a month",
    description: "For any clothing purchases this month, buy second-hand (thrift stores, eBay, Depop) instead of fast-fashion items.",
    impactDescription: "Prevents ~25 kg CO2e per clothing item by eliminating supply chain manufacturing footprint.",
    category: "shopping",
    estimatedCo2eReductionKg: "25.0000",
    feasibilityScore: 70,
    tierLevel: 2,
    isActive: true,
  },
  {
    title: "Install smart power strips",
    description: "Connect your home entertainment center and office desk to smart power strips that auto-power down standby devices when not in use.",
    impactDescription: "Reduces household standby energy footprint by ~15 kg CO2e per month.",
    category: "energy",
    estimatedCo2eReductionKg: "15.0000",
    feasibilityScore: 82,
    tierLevel: 2,
    isActive: true,
  },
  {
    title: "Line dry clothes instead of tumble drying",
    description: "Tumble dryers are home energy hogs. Dry your clothes on an outdoor line or indoor drying rack this week.",
    impactDescription: "Saves ~2.0 kg CO2e per load of laundry.",
    category: "energy",
    estimatedCo2eReductionKg: "2.0000",
    feasibilityScore: 80,
    tierLevel: 2,
    isActive: true,
  },

  // ─── TIER 3: LIFESTYLE LEVERS ───
  {
    title: "Take the train instead of a domestic flight",
    description: "For your next domestic trip under 400 miles, take an Amtrak train instead of flying. Train travel emissions are 12x lower than commercial aviation.",
    impactDescription: "Avoids ~220 kg CO2e compared to a short-haul flight.",
    category: "transport",
    estimatedCo2eReductionKg: "220.0000",
    feasibilityScore: 50,
    tierLevel: 3,
    isActive: true,
  },
  {
    title: "Install a home heat pump",
    description: "Replace a gas furnace or baseboard heaters with a high-efficiency electric heat pump. Heat pumps transfer heat rather than generate it, making them 400% efficient.",
    impactDescription: "Saves ~1,800 kg CO2e per year of space heating.",
    category: "energy",
    estimatedCo2eReductionKg: "1800.0000",
    feasibilityScore: 30,
    tierLevel: 3,
    isActive: true,
  },
  {
    title: "Transition to a fully plant-based diet",
    description: "Adopt a plant-based (vegan) lifestyle, eliminating all animal products (meat, dairy, eggs) from your diet.",
    impactDescription: "Avoids ~1,500 kg CO2e per year compared to an average omnivorous diet.",
    category: "diet",
    estimatedCo2eReductionKg: "125.0000", // monthly equivalent saved
    feasibilityScore: 40,
    tierLevel: 3,
    isActive: true,
  },
  {
    title: "Go car-free or swap to EV",
    description: "Sell your gas car and commit to walking, biking, and transit, or upgrade to a fully electric vehicle powered by green grid charging.",
    impactDescription: "Avoids ~3,200 kg CO2e per year.",
    category: "transport",
    estimatedCo2eReductionKg: "260.0000", // monthly equivalent saved
    feasibilityScore: 25,
    tierLevel: 3,
    isActive: true,
  },
];
