export const seedEmissionFactors = [
  // ─── DIET EMISSION FACTORS (kg CO2e per unit) ───
  {
    source: "DEFRA",
    category: "diet",
    subcategory: "beef",
    activityUnit: "kg",
    factorKgCo2e: "27.0000",
    region: "US",
    metadata: { name: "Beef mince/steak" },
  },
  {
    source: "DEFRA",
    category: "diet",
    subcategory: "chicken",
    activityUnit: "kg",
    factorKgCo2e: "6.9000",
    region: "US",
    metadata: { name: "Chicken breast/poultry" },
  },
  {
    source: "DEFRA",
    category: "diet",
    subcategory: "lentils",
    activityUnit: "kg",
    factorKgCo2e: "0.9000",
    region: "US",
    metadata: { name: "Lentils/beans/legumes" },
  },
  {
    source: "DEFRA",
    category: "diet",
    subcategory: "dairy_milk",
    activityUnit: "kg",
    factorKgCo2e: "3.2000",
    region: "US",
    metadata: { name: "Dairy milk (1 Liter)" },
  },
  {
    source: "DEFRA",
    category: "diet",
    subcategory: "oat_milk",
    activityUnit: "kg",
    factorKgCo2e: "0.9000",
    region: "US",
    metadata: { name: "Oat milk (1 Liter)" },
  },
  {
    source: "DEFRA",
    category: "diet",
    subcategory: "almond_milk",
    activityUnit: "kg",
    factorKgCo2e: "0.7000",
    region: "US",
    metadata: { name: "Almond milk (1 Liter)" },
  },
  {
    source: "DEFRA",
    category: "diet",
    subcategory: "cheese",
    activityUnit: "kg",
    factorKgCo2e: "13.5000",
    region: "US",
    metadata: { name: "Cheese/butter" },
  },
  {
    source: "DEFRA",
    category: "diet",
    subcategory: "vegetables",
    activityUnit: "kg",
    factorKgCo2e: "0.5000",
    region: "US",
    metadata: { name: "Fresh vegetables" },
  },
  {
    source: "DEFRA",
    category: "diet",
    subcategory: "coffee",
    activityUnit: "kg",
    factorKgCo2e: "8.4000",
    region: "US",
    metadata: { name: "Coffee beans/grounds" },
  },

  // ─── TRANSPORT EMISSION FACTORS ───
  {
    source: "EPA",
    category: "transport",
    subcategory: "gasoline",
    activityUnit: "liter",
    factorKgCo2e: "2.3100",
    region: "US",
    metadata: { name: "Gasoline fuel (E10)" },
  },
  {
    source: "EPA",
    category: "transport",
    subcategory: "diesel",
    activityUnit: "liter",
    factorKgCo2e: "2.6800",
    region: "US",
    metadata: { name: "Diesel fuel" },
  },
  {
    source: "DEFRA",
    category: "transport",
    subcategory: "passenger_car",
    activityUnit: "mile",
    factorKgCo2e: "0.4000",
    region: "US",
    metadata: { name: "Average passenger car drive" },
  },
  {
    source: "DEFRA",
    category: "transport",
    subcategory: "public_transit",
    activityUnit: "mile",
    factorKgCo2e: "0.1200",
    region: "US",
    metadata: { name: "Public transport (bus/rail) per passenger-mile" },
  },
  {
    source: "DEFRA",
    category: "transport",
    subcategory: "flight_short",
    activityUnit: "mile",
    factorKgCo2e: "0.2500",
    region: "US",
    metadata: { name: "Short-haul domestic flight per passenger-mile" },
  },
  {
    source: "DEFRA",
    category: "transport",
    subcategory: "flight_long",
    activityUnit: "mile",
    factorKgCo2e: "0.1800",
    region: "US",
    metadata: { name: "Long-haul international flight per passenger-mile" },
  },

  // ─── ENERGY EMISSION FACTORS ───
  {
    source: "EPA",
    category: "energy",
    subcategory: "electricity",
    activityUnit: "kWh",
    factorKgCo2e: "0.3850",
    region: "US",
    metadata: { name: "Average grid electricity intensity" },
  },
  {
    source: "EPA",
    category: "energy",
    subcategory: "natural_gas",
    activityUnit: "kWh",
    factorKgCo2e: "0.1810",
    region: "US",
    metadata: { name: "Natural gas combustion" },
  },

  // ─── SHOPPING EMISSION FACTORS (kg CO2e per USD spent) ───
  {
    source: "Climatiq",
    category: "shopping",
    subcategory: "clothing",
    activityUnit: "USD",
    factorKgCo2e: "0.4500",
    region: "US",
    metadata: { name: "Fashion/apparel spending" },
  },
  {
    source: "Climatiq",
    category: "shopping",
    subcategory: "electronics",
    activityUnit: "USD",
    factorKgCo2e: "0.6800",
    region: "US",
    metadata: { name: "Electronics/appliances spending" },
  },
  {
    source: "Climatiq",
    category: "shopping",
    subcategory: "general",
    activityUnit: "USD",
    factorKgCo2e: "0.2200",
    region: "US",
    metadata: { name: "General merchandise/retail" },
  },
];
