export const seedMerchantCategories = [
  {
    merchantPattern: "shell",
    category: "transport",
    subcategory: "fuel",
    defaultEmissionFactor: "0.8500", // kg CO2e per dollar spent
    confidenceScore: 90,
  },
  {
    merchantPattern: "chevron",
    category: "transport",
    subcategory: "fuel",
    defaultEmissionFactor: "0.8500",
    confidenceScore: 90,
  },
  {
    merchantPattern: "whole foods",
    category: "diet",
    subcategory: "groceries",
    defaultEmissionFactor: "0.2800",
    confidenceScore: 85,
  },
  {
    merchantPattern: "safeway",
    category: "diet",
    subcategory: "groceries",
    defaultEmissionFactor: "0.2600",
    confidenceScore: 85,
  },
  {
    merchantPattern: "walmart",
    category: "shopping",
    subcategory: "general",
    defaultEmissionFactor: "0.2200",
    confidenceScore: 80,
  },
  {
    merchantPattern: "target",
    category: "shopping",
    subcategory: "general",
    defaultEmissionFactor: "0.2400",
    confidenceScore: 80,
  },
  {
    merchantPattern: "amazon",
    category: "shopping",
    subcategory: "general",
    defaultEmissionFactor: "0.3200",
    confidenceScore: 85,
  },
  {
    merchantPattern: "uber",
    category: "transport",
    subcategory: "taxi",
    defaultEmissionFactor: "0.4000",
    confidenceScore: 85,
  },
  {
    merchantPattern: "delta",
    category: "transport",
    subcategory: "flights",
    defaultEmissionFactor: "1.1000",
    confidenceScore: 90,
  },
  {
    merchantPattern: "united airlines",
    category: "transport",
    subcategory: "flights",
    defaultEmissionFactor: "1.1000",
    confidenceScore: 90,
  },
  {
    merchantPattern: "starbucks",
    category: "diet",
    subcategory: "dining",
    defaultEmissionFactor: "0.1800",
    confidenceScore: 85,
  },
  {
    merchantPattern: "mcdonalds",
    category: "diet",
    subcategory: "dining",
    defaultEmissionFactor: "0.3500",
    confidenceScore: 85,
  },
  {
    merchantPattern: "netflix",
    category: "other",
    subcategory: "entertainment",
    defaultEmissionFactor: "0.0500",
    confidenceScore: 75,
  },
  {
    merchantPattern: "spotify",
    category: "other",
    subcategory: "entertainment",
    defaultEmissionFactor: "0.0400",
    confidenceScore: 75,
  },
  {
    merchantPattern: "pg&e",
    category: "energy",
    subcategory: "electric_gas",
    defaultEmissionFactor: "1.4500",
    confidenceScore: 95,
  },
  {
    merchantPattern: "coned",
    category: "energy",
    subcategory: "electric_gas",
    defaultEmissionFactor: "1.3800",
    confidenceScore: 95,
  },
  {
    merchantPattern: "patagonia",
    category: "shopping",
    subcategory: "clothing",
    defaultEmissionFactor: "0.1500", // low carbon due to sustainability focus
    confidenceScore: 80,
  },
  {
    merchantPattern: "apple",
    category: "shopping",
    subcategory: "electronics",
    defaultEmissionFactor: "0.5800",
    confidenceScore: 85,
  },
];
